# Generated by Django 4.1 on 2023-01-31 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_alter_category_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, null=True, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='FollowSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_sellers', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное - продавцы',
                'verbose_name_plural': 'Избранное - продавцы',
                'unique_together': {('user', 'follow_seller')},
            },
        ),
        migrations.CreateModel(
            name='FollowAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ads', to='ads.ads', verbose_name='Избранное объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное - объявления',
                'verbose_name_plural': 'Избранное - объявления',
                'unique_together': {('user', 'follow_ads')},
            },
        ),
    ]
